export type ModelProvider =
  | "openai"
  | "google"
  | "anthropic"
  | "mistral"
  | "groq"
  | "perplexity"
  | "comet"
  | "routerai"
  | "deepseek"
  | "ollama"
  | "openrouter"
  | "llamaindex"
  | "custom"
